[platformio]
default_envs = fsm_nested_switch_avr_n4

src_dir = output/generated_fsm

[env]
platform = atmelavr
board = uno
framework = arduino

monitor_speed = 9600

[env:fsm_nested_switch_avr_n4]
build_src_filter = +<fsm_nested_switch_avr_n4.cpp> -<*>

[env:fsm_nested_switch_avr_n8]
build_src_filter = +<fsm_nested_switch_avr_n8.cpp> -<*>

[env:fsm_nested_switch_avr_n16]
build_src_filter = +<fsm_nested_switch_avr_n16.cpp> -<*>

[env:fsm_nested_switch_avr_n32]
build_src_filter = +<fsm_nested_switch_avr_n32.cpp> -<*>

[env:fsm_nested_switch_avr_n64]
build_src_filter = +<fsm_nested_switch_avr_n64.cpp> -<*>

[env:fsm_nested_switch_avr_n128]
build_src_filter = +<fsm_nested_switch_avr_n128.cpp> -<*>

[env:fsm_array_of_structs_avr_n4]
build_src_filter = +<fsm_array_of_structs_avr_n4.cpp> -<*>

[env:fsm_array_of_structs_avr_n8]
build_src_filter = +<fsm_array_of_structs_avr_n8.cpp> -<*>

[env:fsm_array_of_structs_avr_n16]
build_src_filter = +<fsm_array_of_structs_avr_n16.cpp> -<*>

[env:fsm_array_of_structs_avr_n32]
build_src_filter = +<fsm_array_of_structs_avr_n32.cpp> -<*>

[env:fsm_array_of_structs_avr_n64]
build_src_filter = +<fsm_array_of_structs_avr_n64.cpp> -<*>

[env:fsm_array_of_structs_avr_n128]
build_src_filter = +<fsm_array_of_structs_avr_n128.cpp> -<*>

[env:fsm_indexed_table_avr_n4]
build_src_filter = +<fsm_indexed_table_avr_n4.cpp> -<*>

[env:fsm_indexed_table_avr_n8]
build_src_filter = +<fsm_indexed_table_avr_n8.cpp> -<*>

[env:fsm_indexed_table_avr_n16]
build_src_filter = +<fsm_indexed_table_avr_n16.cpp> -<*>

[env:fsm_indexed_table_avr_n32]
build_src_filter = +<fsm_indexed_table_avr_n32.cpp> -<*>

[env:fsm_indexed_table_avr_n64]
build_src_filter = +<fsm_indexed_table_avr_n64.cpp> -<*>

[env:fsm_indexed_table_avr_n128]
build_src_filter = +<fsm_indexed_table_avr_n128.cpp> -<*>

[env:fsm_state_object_avr_n4]
build_src_filter = +<fsm_state_object_avr_n4.cpp> -<*>

[env:fsm_state_object_avr_n8]
build_src_filter = +<fsm_state_object_avr_n8.cpp> -<*>

[env:fsm_state_object_avr_n16]
build_src_filter = +<fsm_state_object_avr_n16.cpp> -<*>

[env:fsm_state_object_avr_n32]
build_src_filter = +<fsm_state_object_avr_n32.cpp> -<*>

[env:fsm_state_object_avr_n64]
build_src_filter = +<fsm_state_object_avr_n64.cpp> -<*>

[env:fsm_state_object_avr_n128]
build_src_filter = +<fsm_state_object_avr_n128.cpp> -<*>

[env:fsm_hsm_nested_avr_n2]
build_src_filter = +<fsm_hsm_nested_avr_n2.cpp> -<*>

[env:fsm_hsm_nested_avr_n4]
build_src_filter = +<fsm_hsm_nested_avr_n4.cpp> -<*>

[env:fsm_hsm_nested_avr_n6]
build_src_filter = +<fsm_hsm_nested_avr_n6.cpp> -<*>

[env:fsm_hsm_nested_avr_n8]
build_src_filter = +<fsm_hsm_nested_avr_n8.cpp> -<*>

[env:fsm_hsm_nested_avr_n10]
build_src_filter = +<fsm_hsm_nested_avr_n10.cpp> -<*>

[env:fsm_hsm_nested_avr_n12]
build_src_filter = +<fsm_hsm_nested_avr_n12.cpp> -<*>
