[platformio]
default_envs = fsm_hsm_statechart

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_unflags = -Os
build_flags = -O2 -flto

[env:fsm_nested_switch_return]
build_src_filter = +<fsm_nested_switch_return.cpp>

[env:fsm_nested_switch_break]
build_src_filter = +<fsm_nested_switch_break.cpp>

[env:fsm_array_of_structs]
build_src_filter = +<fsm_array_of_structs.cpp>

[env:fsm_indexed_table]
build_src_filter = +<fsm_indexed_table.cpp>

[env:fsm_state_object]
build_src_filter = +<fsm_state_object.cpp>

[env:fsm_hsm_flat]
build_src_filter = +<fsm_hsm_flat.cpp>

[env:fsm_hsm_nested]
build_src_filter = +<fsm_hsm_nested.cpp>

[env:fsm_time_independent_timer0_isr]
build_src_filter = +<fsm_time_independent_timer0_isr.cpp>

; ==============================================================================
; Varijante vernije akademskoj literaturi (vidi citat na vrhu svakog fajla)
; ==============================================================================
[env:fsm_array_of_structs_handler]
build_src_filter = +<fsm_array_of_structs_handler.cpp>

[env:fsm_function_pointers]
build_src_filter = +<fsm_function_pointers.cpp>

[env:fsm_hsm_statechart]
build_src_filter = +<fsm_hsm_statechart.cpp>
